spring.application.name=ERP

#//EXPOSING THE DATABASE URL FOR THE APPLICATION AND DEVELOPMENT'S LOCALHOST SERVER
spring.datasource.url = jdbc:mysql://localhost:3306/erp_data?createDatabaseIfNotExists=true
spring.datasource.username = root
spring.datasource.password = S@nket2004

#//DataBase Driver Class Name
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect


#//Server Configuration
server.port = 8080